Fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,17 +9,25 @@ jobs:
       uses: actions/checkout@v2
     - name: Deps
       run: sudo apt install -y gcc-arm-none-eabi
-    - name: Build FSBL
+    - name: FSBL
       run: |
         set -e
         git clone https://github.com/losfair/embeddedsw
         cd embeddedsw
         git checkout 92c4725f332c00331bd096192bb326ba3af45e8f
-        cd lib/sw_apps/zynq_fsbl/misc
+        cd lib/sw_apps/zynq_fsbl/src
+        make || true # this will fail
+        cd ../misc
         ./copy_bsp.sh
         make CC=arm-none-eabi-gcc
         cd ../src
         make
+    - name: u-boot
+      run: |
+        set -e
+        git clone https://github.com/Xilinx/u-boot-xlnx
+        cd u-boot-xlnx
+        git checkout xilinx-v2019.2
     - name: mkbootimage
       run: |
         set -e
